import 'dotenv/config';
import mongoose from 'mongoose';
import Product from '../models/Product.js';

const base = 'https://sites.kaliumtheme.com/elementor/furniture/wp-content/uploads/2025';

const sampleProducts = [
  { title: 'Compact Nightstand', brand: 'Maison', price: 180, description: 'A compact Scandinavian nightstand in solid oak. Clean lines and a small drawer for essentials. Fits neatly beside any bed.', category: 'Tables', material: 'Oak', stock: 10, images: [`${base}/05/compact-wood-nightstand-15.jpg`, `${base}/05/round-bedside-table-1-600x900.jpeg`], isFeatured: true, dimensions: { length: 45, width: 40, height: 55 } },
  { title: 'Steel Garden Armchair', brand: 'Maison', price: 245, description: 'Weather-resistant steel armchair for patio or garden. Powder-coated finish. Comfortable seat and back.', category: 'Chairs', material: 'Steel', stock: 8, images: [`${base}/05/steel-garden-armchair-1-600x750.jpg`, `${base}/05/steel-garden-armchair-1.jpg`], isNewArrival: true, dimensions: { length: 65, width: 58, height: 82 } },
  { title: 'Tact Mirror', brand: 'Maison', price: 189, description: 'Minimal wall mirror with a thin steel frame. Adds light and depth to any room.', category: 'Home Decor', material: 'Glass, steel', stock: 15, images: [`${base}/05/tact-mirror-2-600x840.jpeg`, `${base}/05/tact-mirror-2.jpeg`], dimensions: { length: 60, width: 5, height: 80 } },
  { title: 'Rocking Armchair', brand: 'Maison', price: 420, description: 'Linen-upholstered rocking armchair. Hand-finished wooden base. Perfect for reading nooks.', category: 'Chairs', material: 'Linen, beech', stock: 5, images: [`${base}/05/linen-rocking-armchair-3.jpeg`, `${base}/05/linen-rocking-armchair-1.jpeg`], colors: [{ name: 'Natural', hex: '#e9e6e3' }, { name: 'Grey', hex: '#8a8a8a' }], dimensions: { length: 85, width: 78, height: 98 } },
  { title: 'Luna Floor Lamp', brand: 'Maison', price: 165, description: 'Elegant floor lamp with a soft, diffused glow. Metal stem and fabric shade.', category: 'Lighting', material: 'Metal, fabric', stock: 12, images: [`${base}/04/luna-floor-lamp-2-500x666.jpg`, `${base}/04/luna-floor-lamp-1.jpg`], isFeatured: true, dimensions: { length: 25, width: 25, height: 165 } },
  { title: 'Compact Boucle Sofa', brand: 'Maison', price: 890, description: 'Two-seater boucle fabric sofa. Soft, durable weave. Solid wood legs. A statement piece for the living room.', category: 'Sofas', material: 'Boucle', stock: 4, images: [`${base}/05/compact-boucle-sofa-11-500x666.jpeg`, `${base}/05/compact-boucle-sofa-1.jpeg`], isNewArrival: true, colors: [{ name: 'Natural', hex: '#e9e6e3' }, { name: 'Grey', hex: '#8a8a8a' }, { name: 'Sand', hex: '#c4a574' }], dimensions: { length: 220, width: 95, height: 78 } },
  { title: 'Amber Capsule Vase', brand: 'Maison', price: 72, description: 'Small amber-toned ceramic vase. Ideal for a single stem or dried arrangement.', category: 'Home Decor', material: 'Ceramic', stock: 25, images: [`${base}/05/amber-capsule-7.jpeg`, `${base}/05/amber-capsule-1.jpeg`] },
  { title: 'Round Bedside Table', brand: 'Maison', price: 195, description: 'Round wooden bedside table with a slim profile. One shelf for books or storage.', category: 'Tables', material: 'Oak', stock: 9, images: [`${base}/05/round-bedside-table-1-600x900.jpeg`, `${base}/05/compact-wood-nightstand-15.jpg`], dimensions: { length: 45, width: 45, height: 52 } },
  { title: 'Glass Display Sideboard', brand: 'Maison', price: 720, description: 'Mid-century inspired sideboard with glass doors. Show off dinnerware or books. Oak frame.', category: 'Tables', material: 'Oak, glass', stock: 3, images: [`${base}/05/glass-display-sideboard-2.jpeg`, `${base}/05/glass-display-sideboard-1.jpeg`], dimensions: { length: 160, width: 45, height: 85 } },
  { title: 'Ambientec Table Lamp', brand: 'Maison', price: 128, description: 'Compact table lamp with a fabric shade. Touch dimmer. Perfect for desks or bedside.', category: 'Lighting', material: 'Metal, fabric', stock: 18, images: [`${base}/05/ambientec-4.jpeg`, `${base}/05/ambientec-1.jpeg`], dimensions: { length: 18, width: 18, height: 42 } },
  { title: 'High-Back Lounge Armchair', brand: 'Maison', price: 580, description: 'High-back lounge armchair in premium fabric. Generous proportions. Wooden legs.', category: 'Chairs', material: 'Fabric, wood', stock: 6, images: [`${base}/05/high-back-lounge-armchair-4-500x666.jpg`, `${base}/05/high-back-lounge-armchair-5-500x666.jpg`], isFeatured: true, colors: [{ name: 'Charcoal', hex: '#36454f' }, { name: 'Cream', hex: '#f5f5dc' }], dimensions: { length: 88, width: 92, height: 105 } },
  { title: 'Double Fabric Bed', brand: 'Maison', price: 1100, description: 'Upholstered double bed with a soft headboard. Neutral fabric. Sturdy wooden frame.', category: 'Beds', material: 'Fabric, wood', stock: 4, images: [`${base}/05/double-fabric-bed-3-500x666.jpg`, `${base}/05/double-fabric-bed-1.jpg`], dimensions: { length: 210, width: 160, height: 95 } },
  { title: 'Stackist Dining Table', brand: 'Maison', price: 650, description: 'Solid wood dining table. Seats six. Clean, modern design. Oiled finish.', category: 'Tables', material: 'Oak', stock: 5, images: [`${base}/05/stackist-12-500x666.jpg`, `${base}/05/stackist-1.jpg`], dimensions: { length: 200, width: 95, height: 76 } },
  { title: 'Check Wool Throw', brand: 'Maison', price: 95, description: 'Soft wool throw in a classic check pattern. Perfect for sofas or beds.', category: 'Textiles', material: 'Wool', stock: 30, images: [`${base}/05/check-wool-5-500x666.jpeg`, `${base}/05/check-wool-1.jpeg`] },
  { title: 'Round Steel Garden Table', brand: 'Maison', price: 380, description: 'Round outdoor table in powder-coated steel. Weather-resistant. Seats four.', category: 'Outdoor', material: 'Steel', stock: 7, images: [`${base}/05/round-steel-garden-table-13-500x666.jpg`, `${base}/05/round-steel-garden-table-1.jpg`], dimensions: { length: 90, width: 90, height: 74 } },
  { title: 'Pet Rug', brand: 'Maison', price: 145, description: 'Durable, washable rug. Neutral tones. Adds texture to living room or bedroom.', category: 'Textiles', material: 'Cotton blend', stock: 20, images: [`${base}/05/pet-rug-1-500x666.jpeg`, `${base}/05/pet-rug-2.jpeg`], isNewArrival: true },
  { title: 'Aluminium Lounge Chair', brand: 'Maison', price: 320, description: 'Lightweight aluminium lounge chair for terrace or garden. Stackable. Cushion optional.', category: 'Outdoor', material: 'Aluminium', stock: 12, images: [`${base}/05/aluminium-lounge-chair-2-500x666.jpeg`, `${base}/05/aluminium-lounge-chair-1.jpeg`], dimensions: { length: 62, width: 58, height: 78 } },
  { title: 'Terracotta Vase Set', brand: 'Maison', price: 88, description: 'Set of two terracotta vases. Hand-thrown. Perfect for greenery or dried flowers.', category: 'Home Decor', material: 'Terracotta', stock: 22, images: [`${base}/05/terracotta-vase-12.jpg`, `${base}/05/terracotta-vase-9.jpg`] },
  { title: 'Upholstered Storage Bed', brand: 'Maison', price: 980, description: 'King-size upholstered bed with built-in storage drawers. Fabric headboard. Practical and elegant.', category: 'Beds', material: 'Fabric, wood', stock: 3, images: [`${base}/05/upholstered-storage-bed-4-500x666.jpg`, `${base}/05/upholstered-storage-bed-1.jpg`], dimensions: { length: 220, width: 200, height: 90 } },
  { title: 'Untitled Throw Blanket', brand: 'Maison', price: 78, description: 'Lightweight throw in a subtle weave. Ideal for sofas or travel.', category: 'Textiles', material: 'Cotton', stock: 35, images: [`${base}/05/untitled-throw-1-500x666.jpg`, `${base}/05/untitled-throw-2.jpg`] },
  { title: 'Cement Garden Table', brand: 'Maison', price: 420, description: 'Rectangular outdoor table in cement composite. Low maintenance. Modern look.', category: 'Outdoor', material: 'Cement composite', stock: 6, images: [`${base}/05/cement-garden-table-10-500x666.jpeg`, `${base}/05/cement-garden-table-1.jpeg`], dimensions: { length: 120, width: 70, height: 72 } },
  { title: 'Apollo Table Lamp', brand: 'Maison', price: 142, description: 'Sculptural table lamp. Ceramic base. Soft, directional light.', category: 'Lighting', material: 'Ceramic, metal', stock: 14, images: [`${base}/05/apollo-17-500x666.jpg`, `${base}/05/apollo-1.jpg`], dimensions: { length: 22, width: 22, height: 48 } },
  { title: 'Dining Chair Set of 2', brand: 'Maison', price: 340, description: 'Set of two dining chairs. Upholstered seat. Wooden frame. Available in several fabrics.', category: 'Chairs', material: 'Wood, fabric', stock: 10, images: [`${base}/05/high-back-lounge-armchair-5-500x666.jpg`, `${base}/05/high-back-lounge-armchair-4-500x666.jpg`], colors: [{ name: 'Natural', hex: '#e9e6e3' }, { name: 'Black', hex: '#1a1a1a' }], dimensions: { length: 52, width: 58, height: 88 } },
  { title: 'Sunao Vase', brand: 'Maison', price: 68, description: 'Minimal ceramic vase. Glazed interior. A quiet accent for any shelf.', category: 'Home Decor', material: 'Ceramic', stock: 28, images: [`${base}/05/sunao-vase-13-819x1024.jpeg`, `${base}/05/sunao-vase-1.jpeg`] },
  { title: 'Upholstered Lounge Chair', brand: 'Maison', price: 520, description: 'Deep-seat lounge chair with soft upholstery. Ideal for living room or study.', category: 'Chairs', material: 'Fabric, wood', stock: 5, images: [`${base}/05/upholstered-3-768x1151.jpg`, `${base}/05/upholstered-8-768x1152.jpg`], isFeatured: true, dimensions: { length: 90, width: 85, height: 92 } },
  { title: 'Lounge Chair Pair', brand: 'Maison', price: 480, description: 'Pair of low-profile lounge chairs. Neutral fabric. Wooden legs.', category: 'Chairs', material: 'Fabric, wood', stock: 4, images: [`${base}/05/upholstered-8-768x1152.jpg`, `${base}/05/upholstered-3-768x1151.jpg`], dimensions: { length: 75, width: 78, height: 72 } },
  { title: 'Compact Wood Nightstand', brand: 'Maison', price: 175, description: 'Slim wood nightstand with one drawer. Fits small bedrooms.', category: 'Tables', material: 'Oak', stock: 11, images: [`${base}/05/compact-wood-nightstand-15.jpg`, `${base}/05/round-bedside-table-1-600x900.jpeg`], dimensions: { length: 42, width: 38, height: 50 } },
  { title: 'Linen Rocking Chair', brand: 'Maison', price: 395, description: 'Rocking chair in linen blend. Gentle curve. Beech wood runners.', category: 'Chairs', material: 'Linen, beech', stock: 7, images: [`${base}/05/linen-rocking-armchair-3.jpeg`, `${base}/05/linen-rocking-armchair-1.jpeg`], dimensions: { length: 82, width: 76, height: 96 } },
  { title: 'Luna Floor Lamp Black', brand: 'Maison', price: 170, description: 'Floor lamp with black metal stem and neutral shade. Adjustable height.', category: 'Lighting', material: 'Metal, fabric', stock: 8, images: [`${base}/04/luna-floor-lamp-2-500x666.jpg`, `${base}/04/luna-floor-lamp-1.jpg`], dimensions: { length: 28, width: 28, height: 168 } },
  { title: 'Glass Sideboard', brand: 'Maison', price: 680, description: 'Storage sideboard with glass-front doors. Two shelves inside. Oak frame.', category: 'Tables', material: 'Oak, glass', stock: 4, images: [`${base}/05/glass-display-sideboard-2.jpeg`, `${base}/05/glass-display-sideboard-1.jpeg`], dimensions: { length: 150, width: 42, height: 82 } },
  { title: 'Steel Garden Armchair Set', brand: 'Maison', price: 460, description: 'Set of two steel garden armchairs. Durable and stylish for outdoor living.', category: 'Outdoor', material: 'Steel', stock: 6, images: [`${base}/05/steel-garden-armchair-1-600x750.jpg`, `${base}/05/steel-garden-armchair-1.jpg`], dimensions: { length: 65, width: 58, height: 82 } },
  { title: 'Tact Mirror Large', brand: 'Maison', price: 220, description: 'Large-format wall mirror. Slim steel frame. Makes any room feel bigger.', category: 'Home Decor', material: 'Glass, steel', stock: 8, images: [`${base}/05/tact-mirror-2-600x840.jpeg`, `${base}/05/tact-mirror-2.jpeg`], dimensions: { length: 80, width: 5, height: 120 } },
  { title: 'Boucle Sofa Grey', brand: 'Maison', price: 920, description: 'Three-seater boucle sofa in grey. Soft, inviting. Solid wood legs.', category: 'Sofas', material: 'Boucle', stock: 3, images: [`${base}/05/compact-boucle-sofa-11-500x666.jpeg`, `${base}/05/compact-boucle-sofa-1.jpeg`], colors: [{ name: 'Grey', hex: '#8a8a8a' }, { name: 'Sand', hex: '#c4a574' }], dimensions: { length: 240, width: 98, height: 80 } },
  { title: 'Wool Check Cushion', brand: 'Maison', price: 45, description: 'Decorative cushion in check-pattern wool. Removable cover.', category: 'Textiles', material: 'Wool', stock: 40, images: [`${base}/05/check-wool-5-500x666.jpeg`, `${base}/05/check-wool-1.jpeg`] },
  { title: 'Terracotta Vase Large', brand: 'Maison', price: 115, description: 'Large terracotta vase. Handcrafted. Statement piece for floor or shelf.', category: 'Home Decor', material: 'Terracotta', stock: 12, images: [`${base}/05/terracotta-vase-9.jpg`, `${base}/05/terracotta-vase-12.jpg`], dimensions: { length: 35, width: 35, height: 55 } },
  { title: 'Cement Garden Table Round', brand: 'Maison', price: 380, description: 'Round cement-effect table for outdoor dining. Seats four comfortably.', category: 'Outdoor', material: 'Cement composite', stock: 5, images: [`${base}/05/cement-garden-table-10-500x666.jpeg`, `${base}/05/cement-garden-table-1.jpeg`], dimensions: { length: 100, width: 100, height: 74 } },
  { title: 'Marble Dining Table', brand: 'Maison', price: 2400, description: 'A statement dining table with a solid Carrara marble top and blackened steel base. Seats eight in effortless grandeur. Each table is unique — marble veining varies naturally.', category: 'Tables', material: 'Carrara marble, blackened steel', stock: 2, images: [`${base}/05/stackist-12-500x666.jpg`, `${base}/05/stackist-1.jpg`], isFeatured: true, dimensions: { length: 240, width: 100, height: 76 } },
  { title: 'Cashmere Lounge Armchair', brand: 'Maison', price: 1650, description: 'An armchair upholstered in 100% Mongolian cashmere, foam-filled for cloud-like comfort. Hand-stitched seams and natural oak legs. A timeless heirloom piece.', category: 'Chairs', material: 'Cashmere, oak', stock: 3, images: [`${base}/05/upholstered-3-768x1151.jpg`, `${base}/05/upholstered-8-768x1152.jpg`], isFeatured: true, isNewArrival: true, colors: [{ name: 'Ivory', hex: '#f5f5dc' }, { name: 'Camel', hex: '#c19a6b' }, { name: 'Charcoal', hex: '#36454f' }], dimensions: { length: 88, width: 86, height: 90 } },
  { title: 'Aged Brass Floor Lamp', brand: 'Maison', price: 485, description: 'Sculptural floor lamp in aged brass with an articulated arm and an adjustable linen shade. Adds warm, directional light to any reading corner or living space.', category: 'Lighting', material: 'Brass, linen', stock: 6, images: [`${base}/04/luna-floor-lamp-2-500x666.jpg`, `${base}/04/luna-floor-lamp-1.jpg`], isNewArrival: true, dimensions: { length: 35, width: 35, height: 180 } },
  { title: 'Merino Wool Bed Throw', brand: 'Maison', price: 220, description: 'Extra-fine Merino wool throw with a herringbone weave. Exceptionally soft, breathable, and temperature-regulating. An elegant addition to any bedroom or sofa.', category: 'Textiles', material: 'Merino wool', stock: 18, images: [`${base}/05/check-wool-5-500x666.jpeg`, `${base}/05/check-wool-1.jpeg`], isNewArrival: true },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/furnistor');
  await Product.deleteMany({});
  await Product.create(sampleProducts);
  console.log('Seeded', sampleProducts.length, 'products');
  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
